# Browser Configuration Settings
# --------------------------

# Main browser settings
browser:
  # Whether to run the browser in headless mode
  headless: false
  
  # Page load timing configurations (in seconds)
  wait_times:
    min_page_load: 3
    max_page_load: 10
    timeout: 300  # General timeout for browser operations
  
  # Browser window display settings
  window:
    width: 1920
    height: 1080
  
  # Debug and visualization settings
  debug:
    highlight_elements: true
  
  # Recording and tracing paths (optional) Null values indicate don't save/record
  recordings:
    save_path: null # True/False to save recordings
    trace_path: null # True/False to save traces (browser_use traces)

# Application-wide settings (moved from .env)
debug_mode: false