# Local Scraper Configuration
# --------------------------

# Profile to use (loads complete configuration from profiles directory)
profile: "wikipedia_extraction"

# Override specific settings from the profile (optional)
scraper:
  # Output file path override
  output_path: "../results/custom_output.json"

# All other configuration is loaded from the profile