# filepath: app/config/secrets.yaml
# RENAME THIS FILE TO secrets.yaml AND FILL IN YOUR SECRETS
# WARNING: NEVER commit this file to version control!

llm:
  openai:
    api_key: "sk-your-openai-key-here"
  
  anthropic:
    api_key: "sk-ant-your-anthropic-key-here"

  azure_openai:
    api_key: "your-azure-openai-key-here"
    endpoint: "https://your-azure-endpoint.com"  # Azure OpenAI endpoint

  google:
    api_key: "your-google-key-here"

  deepseek:
    api_key: "your-deepseek-key-here"

