# Wikipedia Extraction Profile
# --------------------------

# name for profile (For nicer identification in logs/results) Keep lowercase and use underscores/dashes
name: "coal_prices_tabular_multi"

scraper:
  # URL to scrape
  url: "https://www.cctd.com.cn/index.php?m=content&c=index&a=lists&catid=454&data=CCTD%C7%D8%BB%CA%B5%BA%B6%AF%C1%A6%C3%BA%BC%DB%B8%F1&name=CCTD%C7%D8%BB%CA%B5%BA%B6%AF%C1%A6%C3%BA%BC%DB%B8%F1"
  
  # Information to extract
  prompt: 
    task_template: "tabular_extraction"
    context:
      website: "Qinhuangdao Thermal Coal Index秦皇岛动力煤价格指数"
      data_category: "Comprehensive transaction price"
      data_points: "coal prices and month-month increase or decrease for 5500 kcal , 5000 kcal and 4500 kcal"
      no_pages: 3
      filters: null

  
  # Additional context to help with scraping
  additional_context:
    format: "text"
    value: "The information is presented in a table format in Chinese, the table contains the date, with the prices and month-month increase or decrease for 5500, 5000 and 4500 kcal coal prices. The table also has multiple pages, you may use the click feature to click on (XPath=/html/body/div[8]/div[2]/div[3]/div[2]/div[1]/div[9]/div/div[4]/a[2]) to navigate to the next page. Ensure the output is in English and the date is in YYYY-MM-DD format."

  initial_actions:
    - scroll_down: 800
    # - go_to_url: "https://en.wikipedia.org/wiki/Apple"
    # - scroll_down: 4000
    # - go_to_url: "https://en.wikipedia.org/wiki/List_of_Academy_Award%E2%80%93winning_films"

content_structure:
  Coal_Prices:
    date: str
    5500_kcal_price: float
    5500_kcal_change: float
    5000_kcal_price: float
    5000_kcal_change: float
    4500_kcal_price: float
    4500_kcal_change: float


########################################################################
# Optional: Specify the content structure for the scraper to use
# content_structure:
#   <content_type>:
#     <field_name>: <data_type>
#     <field_name>: <data_type>
#
# Example
# content_structure:
#   Film:
#     title: str
#     nominations: int
#     awards_won: int
#     best_picture: bool  # True if the film won the best picture award, False otherwise
#########################################################################
# Avalible Actions
# - scroll_down: <pixels>  # Scroll down the page by a specified number of pixels
# - scroll_up: <pixels>    # Scroll up the page by a specified number of pixels
# - go_to_url: <url>  # Navigate to a specific URL