# Wikipedia Extraction Profile
# --------------------------

# name for profile (For nicer identification in logs/results) Keep lowercase and use underscores/dashes
name: "structured_example"

scraper:
  # URL to scrape
  url: "https://en.wikipedia.org/wiki/List_of_Academy_Award%E2%80%93winning_films"
  
  # Information to extract
  prompt: 
    task_template: "default"
    text: |-
      Extract the list of all nominees for Academy Award best picture for films produced in 2015 from the Wikipedia page.
      
      For each film, extract the following information:
      - Film Title
      - Number of Nominations
      - Number of Awards Won
      - Index (to maintain order)
      - Best Picture Award Status (True if the film won the best picture award, False otherwise)
      - Director of each movie

      The directors information is not available in the table, but clicking on the hyperlink of each film will lead to the film's page where the director's name can be found.

      
  
  # Additional context to help with scraping
  additional_context:
    format: "text"
    value: |-


  initial_actions:
    - scroll_down: 4000


content_structure:
  Film:
    title: str
    nominations: int
    awards_won: int
    index: int
    best_picture: bool
    director: str


########################################################################
# Optional: Specify the content structure for the scraper to use
# content_structure:
#   <content_type>:
#     <field_name>: <data_type>
#     <field_name>: <data_type>
#
# Example
# content_structure:
#   Film:
#     title: str
#     nominations: int
#     awards_won: int
#     best_picture: bool  # True if the film won the best picture award, False otherwise
#########################################################################
# Avalible Actions
# - scroll_down: <pixels>  # Scroll down the page by a specified number of pixels
# - scroll_up: <pixels>    # Scroll up the page by a specified number of pixels
# - go_to_url: <url>  # Navigate to a specific URL